version: '3.8'

networks:
  proxy:
    external: true

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.traefik.rule=Host(`traefik.theovier.de`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.entrypoints=http"

  api:
    build:
      context: apache
    container_name: api
    volumes:
      - /root/zboard-server/:/var/www/html/
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.theovier.de`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.traefik.api.loadbalancer.server.port=8080"

  mariadb:
    image: 'mariadb:10'
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "9081:80"
    networks:
      - proxy
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=300M
