version: '3.8'

services:

  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:admin.theovier.de"
      - "traefik.frontend.entryPoints=https-admin"
      - "traefik.http.routers.api.rule=Host(`admin.theovier.de`)"
      - "traefik.http.routers.api.service=api@internal"

  api:
    build:
      context: apache
    container_name: zboard-api
    restart: unless-stopped
    volumes:
      - /root/zboard-server/:/var/www/html/
    ports:
      - "9080:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.theovier.de`)"
      - "traefik.http.routers.api.entrypoints=web"

  mariadb:
    image: 'mariadb:10'
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "81:80"
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=300M
