version: '3.8'

networks:
  internal:
    driver: bridge
  proxy:
    external: true

services:
  traefik:
    image: "traefik:v2.6"
    container_name: 'traefik'
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/root/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - "--api=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=webmaster@theovier.de"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web,websecure"
      - "traefik.http.routers.traefik.rule=Host(`admin.theovier.de`)"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=https-redirect"
      - "traefik.http.routers.traefik-secure.rule=Host(`admin.theovier.de`)"
      - "traefik.http.routers.traefik-secure.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${DASHBOARD_USER}:${DASHBOARD_PASSWORD}"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
    networks:
      - proxy

#  api:
#    build:
#      context: apache
#    container_name: 'api'
#    volumes:
#      - "/root/zboard-server/:/var/www/html/"
#    restart: unless-stopped
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.api.rule=Host(`api.theovier.de`)"
#      - "traefik.http.routers.api.entrypoints=websecure"
#      - "traefik.http.routers.api.tls.certresolver=myresolver"
#    networks:
#      - proxy
#      - internal

#  db:
#    image: 'mariadb:10'
#    container_name: 'db'
#    restart: unless-stopped
#    ports:
#      - '3306:3306'
#    environment:
#      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
#      MYSQL_DATABASE: '${DB_DATABASE}'
#      MYSQL_USER: '${DB_USERNAME}'
#      MYSQL_PASSWORD: '${DB_PASSWORD}'
#    healthcheck:
#      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
#      retries: 3
#      timeout: 5s
#    networks:
#      - internal
#
#  adminer:
#    image: adminer
#    container_name: 'adminer'
#    restart: unless-stopped
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.phpmyadmin.rule=Host(`db.theovier.de`)"
#      - "traefik.http.routers.phpmyadmin.entrypoints=web"
#    networks:
#      - proxy
#      - internal
#
#  frontend:
#    image: nginx
#    container_name: 'frontend'
#    restart: unless-stopped
#    volumes:
#      - "/root/zboard-client/dist:/usr/share/nginx/html:ro"
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.frontend.rule=Host(`zboard.theovier.de`)"
#      - "traefik.http.routers.frontend.entrypoints=web"
#    command: ['nginx-debug', '-g', 'daemon off;']
#    networks:
#      - proxy
