version: '3.8'

networks:
  proxy:
    external: true
  database:
    driver: bridge
    ipam:
      driver: default
    external: false

services:
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`admin.theovier.de`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.services.traefik.loadBalancer.server.port=8080"
    networks:
      - proxy

  api:
    build:
      context: apache
    container_name: "api"
    volumes:
      - "/root/zboard-server/:/var/www/html/"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.theovier.de`)"
      - "traefik.http.routers.api.entrypoints=web"

  mariadb:
    image: 'mariadb:10'
    container_name: 'mariadb'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 3
      timeout: 5s
    hostname: mariadb
    networks:
      - database

  phpmyadmin:
    image: phpmyadmin
    container_name: "phpmyadmin"
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=300M
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`db.theovier.de`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
    hostname: phpmyadmin
    networks:
      - proxy
      - database
